################### sms config ##################
io:
  sms:
    environment: dev  # ["dev","development","prod","production"]: default prod
    captchaRequiredOperations:
      - login
      #- register
    enableVendor: vanus
    vendors:
      venus:
        captchaCount: 5
        captchaTtlSeconds: 120
        templates:
          - operation: login
            signName: 'venus not use this field'
            templateContent: 'Your code is {code}, valid in 2 minutes.'
            templateParam: '{"code": "%s"}'
            templateCode: 'venus not use this field'
        account: account1
        password: password1
        userId: userid1
        url: http://127.0.0.1:8080/dummyVanusSms
      aliyun:
        captchaCount: 5
        captchaTtlSeconds: 120
        templates:
          - operation: login
            signName: aliyun
            templateContent: 'aliyun not use this field'
            templateParam: '{"code": "%s"}'
            templateCode: T1
        accessKeyId: keyid
        accessSecret: secret
