################### sms config sample ##################
io:
  sms:
    # environement: dev  #dev: not send real message, only log [dev, development, prod, production]
    enableVendor: weiwebs
    captchaRequiredOperations:
      - login
      - register
      - findPassword
      - changeAccount
      - matchSucceed
      - successful
    vendors:
      weiwebs:
        debugMode: 1  # not send message to cell phone
        captchaCount: 5
        captchaTtlSeconds: 120
        templates:
          - operation: login
            templateContent: '【元咕咕】您的短信验证码是：{code}，2分钟内有效'
            templateParam: '{"code": "%s"}'
          - operation: register
            templateContent: '【元咕咕】您的短信验证码是：{code}，2分钟内有效'
            templateParam: '{"code": "%s"}'
          - operation: findPassword
            templateContent: '【元咕咕】您的短信验证码是：{code}，2分钟内有效'
            templateParam: '{"code": "%s"}'
          - operation: changeAccount
            templateContent: '【元咕咕】您正在修改信息，短信验证码是：{code}，2分钟内有效'
            templateParam: '{"code": "%s"}'
          - operation: matchSucceed
            templateContent: '【元咕咕】恭喜您匹配成功，请在2小时内登录进行处理'
          - operation: successful
            templateContent: '【元咕咕】恭喜您对方已经完成处理，请您即刻登录核实'
        account: MXT801633
        pswd: Mxt801636
        url: http://www.weiwebs.cn/msg/HttpBatchSendSM
      aliyun:
        captchaCount: 5
        captchaTtlSeconds: 120
        templates:
          - operation: login
            signName: aliyun
            templateContent: 'aliyun not use this field'
            templateParam: '{"code": "%s"}'
            templateCode: T1
        accessKeyId: keyid
        accessSecret: secret
        